version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
        - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.14
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
    networks:
        - observability

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.14
    container_name: metricbeat
    user: root
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure
    networks:
      - observability

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.17.14
    container_name: heartbeat
    volumes:
    - ./beats/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    environment:
    - setup.kibana.host=kibana:5601
    networks:
      - observability

  apm:
    image: docker.elastic.co/apm/apm-server-oss:7.17.14
    container_name: apm
    volumes:
    - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    restart: on-failure
    networks:
      - observability

networks:
  observability:
    external: true