version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./db:/data/db
      - ./.docker:/docker-entrypoint-initdb.d
    networks:
      - observability
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    container_name: app
    build: .
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MONGODB_DATABASE_URI=$MONGODB_DATABASE_URI
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_DOCKER_PORT=$MONGODB_DOCKER_PORT
    networks:
      - observability
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  observability:
    external: true